config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get     'hello'  => 'static_pages#hello'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  default_scope -> { order('created_at DESC') }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size
  
  private
  
    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy
  
  def show
    @micropost = Micropost.find(params[:id])
    @comment = Comment.new
    @comments = @micropost.comments.includes(:user)
  end
  
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end
  
  private
    
    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end
    
    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_comment.html.erb
<li id="@micropost-<%= @micropost.id %>">
  <%= link_to gravatar_for(comment.user, size: 50), comment.user %>
  <span class="user">
    <%= link_to comment.user.name, comment.user %></span>
  <span class="content">
    <%= comment.content %>
    <%= image_tag comment.picture.url if comment.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(comment.created_at) %> ago.
    <% if current_user?(comment.user) %>
      <%= link_to "delete", micropost_comment_path(@micropost ,comment), method: :delete,
                                      data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
  <%= link_to micropost_path(micropost) do %>
    返信を見る
  <% end %>
  <p class="reply">返信</p>
  <div class="reply_form", style="display:none">
    <%= form_for [micropost, @comment] do |f| %>
      <%= f.text_area :content, class: "form-control"%>
      <%= f.file_field :picture, class: "form-control"%>
      <%= f.submit "SEND", class: "btn btn-info" %>
    <% end %>
  </div>
</li>

app/views/microposts/_micropost.html.haml
%li{:id => "micropost-#{micropost.id}"}
  = link_to gravatar_for(micropost.user, size: 50), micropost.user
  %span.user= link_to micropost.user.name, micropost.user
  %span.content
    = micropost.content
    = image_tag micropost.picture.url if micropost.picture?
  %span.timestamp
    Posted #{time_ago_in_words(micropost.created_at)} ago.
    - if current_user?(micropost.user)
      = link_to "delete", micropost, method: :delete, |
        data: { confirm: "You sure?" }                |

app/views/microposts/show.html.erb
<ol class="microposts">
  <li id="@micropost-<%= @micropost.id %>">
    <%= link_to gravatar_for(@micropost.user, size: 50), @micropost.user %>
    <span class="user">
      <%= link_to @micropost.user.name, @micropost.user %>
    </span>
    <span class="content">
      <%= @micropost.content %>
      <%= image_tag @micropost.picture.url if @micropost.picture? %>
    </span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(@micropost.created_at) %> ago.
      <% if current_user?(@micropost.user) %>
        <%= link_to "delete", @micropost, method: :delete,
                                        data: { confirm: "You sure?" } %>
      <% end %>
    </span>
    <p class="reply">コメントする</p>
    <div class="reply_form", style="display:none">
      <%= form_for [@micropost, @comment] do |f| %>
        <%= f.text_area :content, class: "form-control"%>
        <%= f.file_field :picture, class: "form-control"%>
        <%= f.submit "SEND", class: "btn btn-info" %>
      <% end %>
    </div>
  </li>
  <% @comments.each do |comment| %>
    <%= render partial: "comment", locals: {comment: comment} %>
  <% end %>
</ol>

app/views/microposts/show_reply.html.erb
<h1>返信一覧</h1>

<div>
<% @reply.each do |reply| %>
      <div class="content">
        <%= link_to gravatar_for(reply.user, size: 50), reply.user %>
        <span class="user"><%= link_to reply.user.name, reply.user %></span>
        <p><%= reply.content %></p>
      </div>
<% end %>
</div>